### ISSUE TITLE
so?

### ISSUE THREAD

**Issue by ZoloZiak** [wjk/rosng#1]
so how it look

**Comment by wjk** [comment]
I’m sorry, but I don’t quite understand what you’re asking. I think you’re asking about the status of this project. I have not worked on this project for quite some time, because of logistical issues with upstream ReactOS, and due to other personal obligations.

**Comment by ZoloZiak** [comment]
I apologize that I was unclear in the beginning, but when I saw the goal of the project I thought it was some fork of a beginner programmer.
If I tell the truth I did not expect an answer :smile: 
I do not understand why create such a fork when ReactOS is not yet functional enough to be able to replace Windows XP, aiming at higher version of Windows can it  make only more difficult...
